version: '3.9'

services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - fancyplan

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - fancyplan

networks:
  fancyplan:
